# 数据相关的路径
DATASET_PATH:
    # 节点、节点特征、边关系对应 hdfs 路径
    NODE_INDEX_MAP_HDFS_FILEPATH: "hdfs://harunava/default/user/tiger/warehouse/ies_antispam.db/ecom_seller_uid_reindex_for_onboarding_model_df/date={DATE}/operation_country={COUNTRY}/"
    NODE_FEATURE_HDFS_FILEPATH: "hdfs://harunava/default/user/tiger/warehouse/ies_antispam.db/seller_feature_for_onboarding_model_df/date={DATE}/operation_country={COUNTRY}/"
    EDGE_INDEX_HDFS_PATH: "hdfs://harunava/default/user/tiger/warehouse/ies_antispam.db/ecom_seller_edge_reindex_for_onboarding_model_df/date={DATE}/"
    # EDGE_INDEX 下具体边类型分区名称
    EDGE_TYPES:           
        - register_ip
        - register_did
        - company_register
        - personal_register
        - mobile
        - email
    # ByteNAS 路径, 构图数据先拉取到本地磁盘
    SAVE2FILE_ROOTPATH:  "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/chenyinghao/onboarding_model" # 存储路径的根目录
    NODE_INDEX_MAP_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/chenyinghao/onboarding_model/dataset/node_index/date={DATE}/operation_country={COUNTRY}/"
    NODE_FEATURE_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/chenyinghao/onboarding_model/dataset/node_feature/date={DATE}/operation_country={COUNTRY}/"
    EDGE_INDEX_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/chenyinghao/onboarding_model/dataset/edge_index/date={DATE}/"
    # PYG Graph, ByteNAS 存储路径
    PYG_GRAPH_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/chenyinghao/onboarding_model/pyg_graph/date={DATE}/operation_country={COUNTRY}"
    # Feature Process 存储路径
    FEATURE_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/chenyinghao/onboarding_model/model_res/operation_country={COUNTRY}"
    # Model, ByteNAS 存储路径
    MODEL_SAVE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/chenyinghao/onboarding_model/model_res/GCN/operation_country={COUNTRY}"
# 训练参数
TRAIN_CONF:
    GRAPH_TYPE: "Homo"                      # "Hetero", "Homo"
    CONV_TYPE: "GCN"                          # Model Type  Model List: ["GCN", "GRAPHSAGE", "GIN", "GAT", "HGT", "SAGE"]
    FEATURE_WITH_MMAP: false                  # MMAP 存储 feature，可能导致训练速度降低，uid数量较少时建议关闭
    LABEL_TOPN: 0.999                         # categorical feature select top n% category, tail 1-n% others, =-1 will disable
    DENSE_FEATURE_NORMALIZE: true
    WANDB_PROJECT_NAME: "seller_onboarding_graph_homo_model"     # wandb 项目名
    NUM_ClASS: 2
    EVAL_INTERNAL: 5
    TRAIN_EPOCHS: 500
    BATCH_SIZE: 256
    LEARNING_RATE: 0.00001
    WEIGHT_DECAY: 0
    EARLY_STOP: 100
    TRAIN_SIZE: 1.0
    VAL_SIZE: 0
# 网络参数
NETWORK_CONFIG:
    N_HEADS: 2
    N_LAYERS: 2
    HIDEN_SIZE: 512
    FAN_OUTS: [15, 15]
