# 数据相关的路径
DATASET_PATH:
    # EDGE_INDEX 下具体边类型分区名称
    EDGE_TYPES:           
        - class_to_class
    # ByteNAS 路径, 构图数据先拉取到本地磁盘
    SAVE2FILE_ROOTPATH:  "/Users/chenyi/Documents/sag/Final_Project/code/graph_data" # 存储路径的根目录
    NODE_FEATURE_SAVE2FILE_PATH: "/Users/chenyi/Documents/sag/Final_Project/code/graph_data/{DATA_TYPE}/node_feature" # 存储路径的根目录
    EDGE_INDEX_SAVE2FILE_PATH: "/Users/chenyi/Documents/sag/Final_Project/code/graph_data/{DATA_TYPE}/edge_index"
    # PYG Graph, ByteNAS 存储路径
    PYG_GRAPH_SAVE2FILE_PATH: "/Users/chenyi/Documents/sag/Final_Project/code/graph_data/pyg_graph/{DATA_TYPE}"
    # Feature Process 存储路径
    FEATURE_SAVE2FILE_PATH: "/Users/chenyi/Documents/sag/Final_Project/code/graph_data/feature_processed/"
    # Model, ByteNAS 存储路径
    MODEL_SAVE_PATH: "/Users/chenyi/Documents/sag/Final_Project/code/graph_data/model_res/GCN"
# 训练参数
TRAIN_CONF:
    GRAPH_TYPE: "Homo"                      # "Hetero", "Homo"
    CONV_TYPE: "GCN"                          # Model Type  Model List: ["GCN", "GRAPHSAGE", "GIN", "GAT", "HGT", "SAGE"]
    FEATURE_WITH_MMAP: false                  # MMAP 存储 feature，可能导致训练速度降低，uid数量较少时建议关闭
    LABEL_TOPN: 0.999                         # categorical feature select top n% category, tail 1-n% others, =-1 will disable
    DENSE_FEATURE_NORMALIZE: true
    WANDB_PROJECT_NAME: "object_construction_node_classify_gnn_model"     # wandb 项目名
    NUM_ClASS: 2
    EVAL_INTERNAL: 5
    TRAIN_EPOCHS: 100
    BATCH_SIZE: 128
    LEARNING_RATE: 0.0001
    WEIGHT_DECAY: 0.001
    EARLY_STOP: 30
    TRAIN_SIZE: 1.0
    VAL_SIZE: 0
# 网络参数
NETWORK_CONFIG:
    N_HEADS: 2
    N_LAYERS: 2
    HIDEN_SIZE: 512
    FAN_OUTS: [10, 10]
