# 数据相关的路径
DATASET_PATH:
    # 节点、节点特征、边关系对应 hdfs 路径
    NODE_FEATURE_HDFS_FILEPATH: "hdfs://harunava/default/user/tiger/warehouse/ies_antispam.db/ecom_seller_feature_for_pretrain_model_df/date={DATE}/"
    EDGE_INDEX_HDFS_PATH: "hdfs://harunava/default/user/tiger/warehouse/ies_antispam.db/ecom_seller_homo_edge_reindex_for_pretrain_model_df/date={DATE}/"

    # ByteNAS 路径, 构图数据先拉取到本地磁盘
    SAVE2FILE_ROOTPATH:  "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/dongchenhui.0711/pretrain_model" # 存储路径的根目录
    NODE_FEATURE_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/dongchenhui.0711/pretrain_model/node_feature/date={DATE}/"
    EDGE_INDEX_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/dongchenhui.0711/pretrain_model/edge_index/date={DATE}/"

    # PYG Graph, ByteNAS 存储路径
    PYG_GRAPH_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/dongchenhui.0711/pretrain_model/homo_pyg_graph/date={DATE}"

    # Feature Process 存储路径
    FEATURE_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/dongchenhui.0711/pretrain_model/feature_process"

    # Model, ByteNAS 存储路径
    MODEL_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/dongchenhui.0711/pretrain_model/model_ckp"

    # Pretrain Model
    PRETRAIN_MODEL_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/dongchenhui.0711/pretrain_model/model_ckp/GraphCL.GraphSAGE.64.64.0.001.1e-05.pth"

    # Embedding Save Path
    Embedding_SAVE2FILE_PATH: "/mnt/bn/global-ecom-risk-management-sharenas/mlx/users/dongchenhui.0711/pretrain_model/model_embedding/"

# 训练参数
TRAIN_CONF:
    LABEL_TOPN: 0.99                         # categorical feature select top n% category, tail 1-n% others, =-1 will disable
    DENSE_FEATURE_NORMALIZE: true
    CAT_FEATURE_NORMALIZE: true
    SEED: 42
    DEVICE: 0
    MODEL_TYPE: 'GraphMAE'              # ['GraphCL', 'GraphclClusterLoss', 'GraphMAE']
    CONV_TYPE: 'GAT'                    # ['GAT', 'GCN', 'GraphSAGE', 'GIN', 'GCov', 'GraphTransformer']
    HIDDEN_DIM: 512
    OUT_DIM: 128
    NUM_LAYER: 2
    NUM_HEADS: 4
    TRAIN_EPOCHS: 200
    BATCH_SIZE: 128
    LEARNING_RATE: 0.01
    WEIGHT_DECAY: 0.0001
    AUG1: 'dropN'                             # ['dropN', 'permE', 'maskN'] 
    AUG2: 'maskN'
    AUG_RATIO: 0.3
    MASK_RATE: 0.3
    DROP_EDGE_RATE: 0.0
    REPLACE_RATE: 0.05

# 重构图生成时使用的ANN参数
ANN_CONFIG:
    TOPK: 10                                 # ANN召回时为每一个节点分配topk数量
    THRESHOLD: 0.9                           # ANN召回时限制topk的embedding相似度下限
