_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.6
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.6
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
DATASET_PATH:
    value:
        EDGE_INDEX_SAVE2FILE_PATH: /Users/chenyi/Documents/sag/Final_Project/code/graph_data/{DATA_TYPE}/edge_index
        EDGE_TYPES:
            - class_to_class
        FEATURE_SAVE2FILE_PATH: /Users/chenyi/Documents/sag/Final_Project/code/graph_data/feature_processed/
        MODEL_SAVE_PATH: /Users/chenyi/Documents/sag/Final_Project/code/graph_data/model_res/GCN
        NODE_FEATURE_SAVE2FILE_PATH: /Users/chenyi/Documents/sag/Final_Project/code/graph_data/{DATA_TYPE}/node_feature
        PYG_GRAPH_SAVE2FILE_PATH: /Users/chenyi/Documents/sag/Final_Project/code/graph_data/pyg_graph/{DATA_TYPE}
        SAVE2FILE_ROOTPATH: /Users/chenyi/Documents/sag/Final_Project/code/graph_data
NETWORK_CONFIG:
    value:
        FAN_OUTS:
            - 10
            - 10
        HIDEN_SIZE: 256
        N_HEADS: 4
        N_LAYERS: 2
TRAIN_CONF:
    value:
        BATCH_SIZE: 512
        CONV_TYPE: GCN
        DENSE_FEATURE_NORMALIZE: true
        EARLY_STOP: 50
        EVAL_INTERNAL: 5
        FEATURE_WITH_MMAP: false
        GRAPH_TYPE: Homo
        LABEL_TOPN: 0.999
        LEARNING_RATE: 1e-06
        NUM_ClASS: 2
        TRAIN_EPOCHS: 500
        TRAIN_SIZE: 1
        VAL_SIZE: 0
        WANDB_PROJECT_NAME: object_construction_node_classify_gnn_model
        WEIGHT_DECAY: 1e-05
